version: '3'

services:
    nginx:
        image: nginx:1.16
        ports:
            - "80:8000"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - ./nginx/log:/var/log/nginx
            - ./static:/static
        depends_on:
            - python
        environment:
            TZ: 'Asia/Tokyo'

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: natsume
            MYSQL_DATABASE: pf
            MYSQL_USER: pf
            MYSQL_PASSWORD: pf
            TZ: 'Asia/Tokyo'
        volumes:
            - ./mysql:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
            - ./backup:/var/lib/backup
#        command: mysqld --skip-grant-tables --skip-networking 

    python:
        build: ./python
        command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
        volumes:
            - ./src:/code
            - ./static:/static
        expose:
            - "8001"
        depends_on:
            - db
        environment:
            TZ: 'Asia/Tokyo'
