# Generated by Django 3.0.4 on 2020-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140, verbose_name='やること')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
            ],
        ),
    ]
