# Generated by Django 3.0.4 on 2020-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200928_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='message',
            field=models.CharField(max_length=140, verbose_name='todo app'),
        ),
    ]
