machine:
  python:
    version: 3.5.2
  timezone: Asia/Tokyo

database:
  override:
#    設定ファイルを上書き
    - mv sample/settings.ci.py sample/settings.py
#    urls.py差し替え
    - mv sample/urls.py sample/urls.py.org
    - mv sample/urls.ci.py sample/urls.py

#    マイグレーションファイル作成
    - python ./manage.py makemigrations accounts
#    マイグレーションファイルをDBへ反映する
    - python ./manage.py migrate

#    差し替えていたurls.pyを元に戻す
    - mv sample/urls.py.org sample/urls.py
test:
  override:
    - coverage run --source=accounts manage.py test accounts
    - coverage html
  post:
    - mv cover $CIRCLE_ARTIFACTS
